# Generated by Django 4.2.1 on 2023-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "gym_cd",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("gym_nm", models.CharField(max_length=100, unique=True)),
                ("gym_hp_link", models.CharField(max_length=255, unique=True)),
                ("gym_addr", models.CharField(max_length=100)),
                ("gym_phone_reserve_link", models.CharField(max_length=255)),
                ("gym_net_reserve_link", models.CharField(max_length=255)),
            ],
        ),
    ]
